export const ROUTE_CHANGED = "ROUTE_CHANGED";
export const ROUTE_CHANGE = "ROUTE_CHANGE";
export const ROUTE_CONTEXT_UPDATED = "ROUTE_CONTEXT_UPDATED";

export default {
    ROUTE_CHANGED, ROUTE_CHANGE, ROUTE_CONTEXT_UPDATED
}